export interface AcademyClient {
  id: number;
  name: string;
  gender:string;
  phone:number;
  Guadian:string;
  numberOfGuardian:number;
  address: string;
  Duration: string;
  enrollmentDay: string;
  courseEnrolled: string;
  amountPaid:number;
  balance?:number;
}

export const AcademyClients: AcademyClient[] = [
  {
    id: 1,
    name: "Chinwe Okorie",
    gender: "Female",
    phone: 2348012345678,
    Guadian: "Mary Okorie",
    numberOfGuardian: 1,
    address: "123 Lagos Street, Lagos, Nigeria",
    Duration: "3 months",
    enrollmentDay: "2026-01-15",
    courseEnrolled: "Frontend Web Development",
    amountPaid: 50000,
    balance: 10000,
  },
  {
    id: 2,
    name: "Emeka Nwosu",
    gender: "Male",
    phone: 2348098765432,
    Guadian: "James Nwosu",
    numberOfGuardian: 1,
    address: "45 Abuja Avenue, Abuja, Nigeria",
    Duration: "6 months",
    enrollmentDay: "2026-02-01",
    courseEnrolled: "Backend Web Development",
    amountPaid: 80000,
    balance: 20000,
  },
  {
    id: 3,
    name: "Adaeze Uche",
    gender: "Female",
    phone: 2348023456789,
    Guadian: "Nkechi Uche",
    numberOfGuardian: 1,
    address: "78 Port Harcourt Road, Rivers, Nigeria",
    Duration: "1 month",
    enrollmentDay: "2026-01-20",
    courseEnrolled: "Graphic Design",
    amountPaid: 25000,
    balance: 0,
  },
  {
    id: 4,
    name: "Obinna Chukwu",
    gender: "Male",
    phone: 2348034567890,
    Guadian: "Patience Chukwu",
    numberOfGuardian: 1,
    address: "12 Enugu Street, Enugu, Nigeria",
    Duration: "3 months",
    enrollmentDay: "2026-01-10",
    courseEnrolled: "UI/UX Design",
    amountPaid: 40000,
    balance: 5000,
  },
  {
    id: 5,
    name: "Ijeoma Okafor",
    gender: "Female",
    phone: 2348056789012,
    Guadian: "Chinelo Okafor",
    numberOfGuardian: 1,
    address: "90 Ibadan Lane, Oyo, Nigeria",
    Duration: "6 months",
    enrollmentDay: "2026-02-05",
    courseEnrolled: "Fullstack Web Development",
    amountPaid: 120000,
    balance: 0,
  },
  {
    id: 6,
    name: "Tunde Adebayo",
    gender: "Male",
    phone: 2348078901234,
    Guadian: "Folake Adebayo",
    numberOfGuardian: 1,
    address: "56 Lagos Island, Lagos, Nigeria",
    Duration: "1 month",
    enrollmentDay: "2026-01-25",
    courseEnrolled: "Digital Marketing",
    amountPaid: 30000,
    balance: 5000,
  },
  {
    id: 7,
    name: "Ngozi Eze",
    gender: "Female",
    phone: 2348089012345,
    Guadian: "Chinwe Eze",
    numberOfGuardian: 1,
    address: "23 Owerri Street, Imo, Nigeria",
    Duration: "3 months",
    enrollmentDay: "2026-01-30",
    courseEnrolled: "Data Analytics",
    amountPaid: 60000,
    balance: 10000,
  },
  {
    id: 8,
    name: "Kelechi Nnamdi",
    gender: "Male",
    phone: 2348090123456,
    Guadian: "Amaka Nnamdi",
    numberOfGuardian: 1,
    address: "88 Onitsha Road, Anambra, Nigeria",
    Duration: "6 months",
    enrollmentDay: "2026-02-10",
    courseEnrolled: "Cybersecurity",
    amountPaid: 90000,
    balance: 15000,
  },
  {
    id: 9,
    name: "Funke Adeyemi",
    gender: "Female",
    phone: 2348101234567,
    Guadian: "Adebimpe Adeyemi",
    numberOfGuardian: 1,
    address: "11 Ibadan Road, Oyo, Nigeria",
    Duration: "1 month",
    enrollmentDay: "2026-01-18",
    courseEnrolled: "Basic Computer Training",
    amountPaid: 20000,
    balance: 0,
  },
  {
    id: 10,
    name: "Chidera Obi",
    gender: "Female",
    phone: 2348112345678,
    Guadian: "Emeka Obi",
    numberOfGuardian: 1,
    address: "34 Enugu Road, Enugu, Nigeria",
    Duration: "3 months",
    enrollmentDay: "2026-01-12",
    courseEnrolled: "Frontend Web Development",
    amountPaid: 50000,
    balance: 5000,
  },
  {
    id: 11,
    name: "Ibrahim Musa",
    gender: "Male",
    phone: 2348123456789,
    Guadian: "Aisha Musa",
    numberOfGuardian: 1,
    address: "67 Kano Street, Kano, Nigeria",
    Duration: "6 months",
    enrollmentDay: "2026-02-03",
    courseEnrolled: "Backend Web Development",
    amountPaid: 85000,
    balance: 15000,
  },
  {
    id: 12,
    name: "Blessing Okeke",
    gender: "Female",
    phone: 2348134567890,
    Guadian: "Ngozi Okeke",
    numberOfGuardian: 1,
    address: "19 Onitsha Avenue, Anambra, Nigeria",
    Duration: "1 month",
    enrollmentDay: "2026-01-22",
    courseEnrolled: "Graphic Design",
    amountPaid: 25000,
    balance: 0,
  },
  {
    id: 13,
    name: "Samuel Adekunle",
    gender: "Male",
    phone: 2348145678901,
    Guadian: "Funmi Adekunle",
    numberOfGuardian: 1,
    address: "40 Lagos Road, Lagos, Nigeria",
    Duration: "3 months",
    enrollmentDay: "2026-01-14",
    courseEnrolled: "UI/UX Design",
    amountPaid: 45000,
    balance: 5000,
  },
  {
    id: 14,
    name: "Uchechi Nwankwo",
    gender: "Female",
    phone: 2348156789012,
    Guadian: "Chinasa Nwankwo",
    numberOfGuardian: 1,
    address: "72 Owerri Road, Imo, Nigeria",
    Duration: "6 months",
    enrollmentDay: "2026-02-07",
    courseEnrolled: "Fullstack Web Development",
    amountPaid: 120000,
    balance: 0,
  },
  {
    id: 15,
    name: "Olusegun Afolabi",
    gender: "Male",
    phone: 2348167890123,
    Guadian: "Modupe Afolabi",
    numberOfGuardian: 1,
    address: "55 Lagos Island, Lagos, Nigeria",
    Duration: "1 month",
    enrollmentDay: "2026-01-27",
    courseEnrolled: "Digital Marketing",
    amountPaid: 35000,
    balance: 5000,
  },
  {
    id: 16,
    name: "Amaka Eze",
    gender: "Female",
    phone: 2348178901234,
    Guadian: "Ngozi Eze",
    numberOfGuardian: 1,
    address: "21 Onitsha Street, Anambra, Nigeria",
    Duration: "3 months",
    enrollmentDay: "2026-01-29",
    courseEnrolled: "Data Analytics",
    amountPaid: 65000,
    balance: 10000,
  },
  {
    id: 17,
    name: "Chuka Nwafor",
    gender: "Male",
    phone: 2348189012345,
    Guadian: "Ijeoma Nwafor",
    numberOfGuardian: 1,
    address: "39 Enugu Road, Enugu, Nigeria",
    Duration: "6 months",
    enrollmentDay: "2026-02-12",
    courseEnrolled: "Cybersecurity",
    amountPaid: 95000,
    balance: 5000,
  },
  {
    id: 18,
    name: "Ngozi Okonkwo",
    gender: "Female",
    phone: 2348190123456,
    Guadian: "Chika Okonkwo",
    numberOfGuardian: 1,
    address: "15 Lagos Street, Lagos, Nigeria",
    Duration: "1 month",
    enrollmentDay: "2026-01-19",
    courseEnrolled: "Basic Computer Training",
    amountPaid: 22000,
    balance: 0,
  },
  {
    id: 19,
    name: "Ifeanyi Kalu",
    gender: "Male",
    phone: 2348201234567,
    Guadian: "Ngozi Kalu",
    numberOfGuardian: 1,
    address: "44 Owerri Street, Imo, Nigeria",
    Duration: "3 months",
    enrollmentDay: "2026-01-11",
    courseEnrolled: "Frontend Web Development",
    amountPaid: 52000,
    balance: 3000,
  },
  {
    id: 20,
    name: "Chinelo Amadi",
    gender: "Female",
    phone: 2348212345678,
    Guadian: "Uche Amadi",
    numberOfGuardian: 1,
    address: "32 Port Harcourt Lane, Rivers, Nigeria",
    Duration: "6 months",
    enrollmentDay: "2026-02-08",
    courseEnrolled: "Fullstack Web Development",
    amountPaid: 125000,
    balance: 0,
  },
];
